name: work
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - numpy
  - scipy
  - matplotlib
  - rasterio
  - rioxarray
  - gdal
  - xarray
  - dask
  - pandas
  - geopandas
  - hvplot
  - opencv
  - pip
  - pyproj
  - python
  - scikit-image
  - tmux
  - seaborn
  - parallel
  - contextily
  - shapely
  - fiona
  - folium
  - cartopy
  - matplotlib-scalebar
  - netcdf4
  - bottleneck
  - ca-certificates
  - certifi
  - openssl
  - ipympl
  - lxml
