name: isnoda
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - cfgrib
  - coloredlogs
  - cython
  - dateparser=0.7.2
  - gcc=8.5.0
  - make
  - nco
  - netCDF4
  - numpy=1.20
  - openmpi=4.1.2
  - pandas
  - pip
  - progressbar2
  - pykrige
  - python=3.7
  - pytz
  - pyyaml
  - regex
  - requests
  - setuptools_scm<4.2
  - scipy
  - siphon
  - urllib3
  - utm
  - xarray
