name: isnoda
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - cfgrib
  - cftime=1.5.2
  - coloredlogs
  - cython
  - dateparser=0.7.2
  - make
  - nco
  - netCDF4
  - numpy=1.20.3
  - openmpi=4.1.2
  - pandas=1.3.5
  - parallel
  - pip
  - progressbar2
  - pykrige
  - python=3.7
  - pytz
  - pyyaml
  - regex=2020.2.20
  - requests
  - setuptools_scm<4.2
  - scipy<1.7.0
  - siphon
  - urllib3
  - utm
  - xarray=0.15.1
