channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - dask-jobqueue
  - gdal
  - h5py
  - netCDF4
  - pip
  - python=3.8
  - rasterio
  - xarray
  - zarr
  - pip:
      - git+https://github.com/UofU-Cryosphere/snow-rs.git@main
