channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - dask-jobqueue
  - gdal
  - netCDF4
  - parallel
  - pip
  - python
  - xarray
  - zarr
  - pip:
      - git+https://github.com/UofU-Cryosphere/snow-rs.git@main
      - spatialnc
